export { default as AppMain } from './AppMain/index.vue'
export { default as NavigationBar } from './NavigationBar/index.vue'
export { default as Sidebar } from './Sidebar/index.vue'
export { default as TagsView } from './TagsView/index.vue'
// export { default as Settings } from './Settings/index.vue'
