# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

node_js:
  - node

# Skipping the Installation Phase
# https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase
install: skip

script:
  - echo "Starting to build. DOCKER_HUB_USERNAME:"
  - echo "$DOCKER_HUB_USERNAME"
  - "docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD"
  - npm run travis:dev_dkr
  - npm run travis:test
  - npm run travis:stage
  - npm run travis:prod

# https://docs.travis-ci.com/user/notifications#default-notification-settings
notifications:
  email:
    on_success: change
    on_failure: always

# https://docs.travis-ci.com/user/encryption-keys#usage
# travis encrypt KEY=value --add
env:
  - DOCKER_HUB_USERNAME: MZWgt8WqwKUh9kSafQ43NUlTvBl7pe8rxONJ3ChlGzVCLUBxCOMzEW3WQLHY1Xf+FYa/HpZXkuX1T5+XAskUO7gHrkYpTm0kFIWI1apgUmq2ZoBHZkvV7lVsL2uQJ7WfnsFYeJQZrsUDWeNkQlUzb/xFUwfFmagAi2d92RA36Oj7nFGEsFnanwOccXM2VmMytRmQWvk6ze4zQ/hnxccw7ckyyB3KJoP34j3ScQGGQKQQw4aK5PC8JkcKj0G1kvmRjbuW33o+R4clKVSiSo/640q0oZFECIwvS0rSzMTxxV5Tz7I9tSnkFsAeBIWUa2d1+nVgMP9WDE7uHbJuHqTrMNLuJTboa3JxXudISa8PE7IPOCMP2rvKe+Y/si1DYjwZbR3LFJ28u5GyV4OmB6GaeElinYHe/hG5A2+mfP9Yb7LUVg7Y2VTa5ZF/Yxf/YP1LTpaS1PeOlSMhuEklx1o3C10SZTQSIUBLnVrBKFNx7G2FW1o0Zf8sZ7ks/3xTiybRbRo3KizTpgweWLa85fuuppiuM9paqrYOHzHQ1SImpr//tykw8+vFx2657Spj691eSIBsD8jP4Dp08OY+Car+52QlaUtlXz7b7ylMmBgo4dMYlpcpWx0aXvpg5Q27+eU2Pub25aDWlbixmrbZMltohR+I64hALyfwwbkFd13RsLU=
  - DOCKER_HUB_PASSWORD: gGg26o3Yf631vPGLTReCnQFWn9MhvUisA2cjJdxOAi50LYo5ZYSWMlaL6qq0WRRbjb2XYy1rHgZ6NwTaetBdAXlO7NjI5QPKmDpn02K5Qh5bg50/p3yqPlGkxHznM6uqUjyl98TwipIIwf3IT7ZgSP8iURtuYxSN0/hTF9B6biIujxYbIaf6aBaG6fjqIIYznMs4YSESMM7v5hUDNuUYkspUgbaMeoHfx6+xZWLlh+oA6OAfLWJKcO9NzRWoX48DTwmgGkEgmJEEpnBGEZ9TKraODARhwC8iRMFUj5KoWDIvB1e1+KME9kYR/thZsh9sBqgBx+DLgUTirge0pKZHPvL6I2dTooCMVr8HB+FBMQxykofrfZhVAAjF67FgpQg1vl7sCTVI3tuwjpaoGMbK29k1wzzabF4iMGmflyEsdXQ1z3Y/rSuoFfh0It2ihVK65gKjGjYjcwZTjox7exQeQSHsAYmZYga9Dmo2oIMapELO59qvTdAVif+gStGdIVOv1wMWQrSilBt1EKwFcEvNVCfu/fb4yOyJkGD6k7KzWBODwa5INpbbx6s+Ucw+2+BX0zIWbRYb50OyNx2kF81xHm3BALViNnUZsPWXoVwG692Pe6djEPFGLyTLRkYuUhdoqoL6Jwe4XYFnSmTQ0i8C1vOKqJuSZpDsM/z8VCJYgQE=
