# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

node_js:
  - node

# Skipping the Installation Phase
# https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase
install: skip

script:
  - echo "Starting to build. DOCKER_HUB_USERNAME:"
  - echo "$DOCKER_HUB_USERNAME"
  - "docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD"
  - npm run travis:dev_dkr
  - npm run travis:test
  - npm run travis:stage
  - npm run travis:prod

# https://docs.travis-ci.com/user/notifications#default-notification-settings
notifications:
  email:
    on_success: change
    on_failure: always
