version: "3.7"

services:
  muscle-and-fitness-admin:
    container_name: muscle-and-fitness-admin-test
    image: "ijohnnymiller/muscle-and-fitness-admin-test:${TAG}"
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ENV: test
        ENV_ALIAS: test
    ports:
      - 8081:80
    volumes:
      - /Users/johnny/docker-file-mapping/exrx-net-crawler/log:/var/log/nginx
